# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'l:\label_check\ui\check.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bo/resource/ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(-1, 40, -1, 50)
        self.formLayout.setObjectName("formLayout")
        self.auto_radio = QtWidgets.QRadioButton(self.widget)
        self.auto_radio.setStyleSheet("font: 75 12pt \"Arial\";")
        self.auto_radio.setChecked(True)
        self.auto_radio.setObjectName("auto_radio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.auto_radio)
        self.manpower_radio = QtWidgets.QRadioButton(self.widget)
        self.manpower_radio.setStyleSheet("font: 75 12pt \"Arial\";")
        self.manpower_radio.setObjectName("manpower_radio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.manpower_radio)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.custom_cb = QtWidgets.QComboBox(self.widget)
        self.custom_cb.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custom_cb.sizePolicy().hasHeightForWidth())
        self.custom_cb.setSizePolicy(sizePolicy)
        self.custom_cb.setMinimumSize(QtCore.QSize(0, 40))
        self.custom_cb.setStyleSheet("padding-left:10px;\n"
"font: 75 15pt \"等线\";\n"
"color: rgb(170, 0, 255);")
        self.custom_cb.setObjectName("custom_cb")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.custom_cb)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.module_cb = QtWidgets.QComboBox(self.widget)
        self.module_cb.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_cb.sizePolicy().hasHeightForWidth())
        self.module_cb.setSizePolicy(sizePolicy)
        self.module_cb.setMinimumSize(QtCore.QSize(0, 40))
        self.module_cb.setStyleSheet("padding-left:10px;\n"
"font: 75 15pt \"等线\";\n"
"color: rgb(170, 0, 255);")
        self.module_cb.setObjectName("module_cb")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.module_cb)
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        self.label_4.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.name_cb = QtWidgets.QComboBox(self.widget)
        self.name_cb.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_cb.sizePolicy().hasHeightForWidth())
        self.name_cb.setSizePolicy(sizePolicy)
        self.name_cb.setMinimumSize(QtCore.QSize(0, 40))
        self.name_cb.setStyleSheet("padding-left:10px;\n"
"font: 75 15pt \"等线\";\n"
"color: rgb(170, 0, 255);")
        self.name_cb.setObjectName("name_cb")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.name_cb)
        self.label_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 40))
        self.label_6.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.pn_cb = QtWidgets.QComboBox(self.widget)
        self.pn_cb.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pn_cb.sizePolicy().hasHeightForWidth())
        self.pn_cb.setSizePolicy(sizePolicy)
        self.pn_cb.setMinimumSize(QtCore.QSize(0, 40))
        self.pn_cb.setStyleSheet("padding-left:10px;\n"
"font: 75 15pt \"等线\";\n"
"color: rgb(170, 0, 255);")
        self.pn_cb.setObjectName("pn_cb")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pn_cb)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setStyleSheet("font: 16pt \"思源黑体 CN Regular\";")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.input_ln = MyLineEdit(self.widget)
        self.input_ln.setMinimumSize(QtCore.QSize(0, 37))
        self.input_ln.setStyleSheet("MyLineEdit {\n"
"    font: 14pt \"黑体\";\n"
"    color:rgb(0, 0, 255);\n"
"    padding-left:20px;\n"
"    border:none;\n"
"    border-bottom:1px solid rgb(0, 0, 0) ;\n"
"\n"
"}\n"
"MyLineEdit:hover,MyLineEdit:focus {\n"
"    border-bottom:1px solid rgb(0, 255, 127);\n"
"}")
        self.input_ln.setText("")
        self.input_ln.setObjectName("input_ln")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.input_ln)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setStyleSheet("font: 16pt \"楷体\";\n"
"color: rgb(75, 0, 225);")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.result_txt = QtWidgets.QLineEdit(self.widget)
        self.result_txt.setEnabled(True)
        self.result_txt.setMinimumSize(QtCore.QSize(0, 50))
        self.result_txt.setStyleSheet("border:1px solid gray;\n"
"border-radius:25px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"Arial\";")
        self.result_txt.setText("")
        self.result_txt.setDragEnabled(False)
        self.result_txt.setReadOnly(True)
        self.result_txt.setClearButtonEnabled(False)
        self.result_txt.setObjectName("result_txt")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.result_txt)
        spacerItem4 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setStyleSheet("border:1px solid gray;\n"
"")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 180, 180, 0))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 180, 180))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 180, 180))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 180, 180))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.ab_author_ac = QtWidgets.QAction(MainWindow)
        self.ab_author_ac.setObjectName("ab_author_ac")
        self.ab_qt_ac = QtWidgets.QAction(MainWindow)
        self.ab_qt_ac.setObjectName("ab_qt_ac")
        self.theme_set_ac = QtWidgets.QAction(MainWindow)
        self.theme_set_ac.setObjectName("theme_set_ac")
        self.edit_plicy_ac = QtWidgets.QAction(MainWindow)
        self.edit_plicy_ac.setObjectName("edit_plicy_ac")
        self.edit_item_ac = QtWidgets.QAction(MainWindow)
        self.edit_item_ac.setObjectName("edit_item_ac")
        self.open_file_ac = QtWidgets.QAction(MainWindow)
        self.open_file_ac.setObjectName("open_file_ac")
        self.close_file_ac = QtWidgets.QAction(MainWindow)
        self.close_file_ac.setObjectName("close_file_ac")
        self.exit_ac = QtWidgets.QAction(MainWindow)
        self.exit_ac.setObjectName("exit_ac")
        self.ab_version_ac = QtWidgets.QAction(MainWindow)
        self.ab_version_ac.setObjectName("ab_version_ac")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.logout_ac = QtWidgets.QAction(MainWindow)
        self.logout_ac.setObjectName("logout_ac")
        self.menu.addSeparator()
        self.menu.addAction(self.open_file_ac)
        self.menu.addAction(self.close_file_ac)
        self.menu.addSeparator()
        self.menu.addSeparator()
        self.menu.addAction(self.logout_ac)
        self.menu.addAction(self.exit_ac)
        self.menu_2.addAction(self.edit_plicy_ac)
        self.menu_2.addAction(self.edit_item_ac)
        self.menu_3.addAction(self.theme_set_ac)
        self.menu_4.addAction(self.ab_qt_ac)
        self.menu_4.addAction(self.ab_version_ac)
        self.menu_4.addAction(self.ab_author_ac)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        self.module_cb.activated['QString'].connect(MainWindow.module_change)
        self.name_cb.activated['QString'].connect(MainWindow.name_change)
        self.input_ln.signal_keyboarded.connect(MainWindow.input_scan)
        self.custom_cb.activated['QString'].connect(MainWindow.custom_change)
        self.auto_radio.toggled['bool'].connect(MainWindow.check_model_change)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "条码验证系统"))
        self.auto_radio.setText(_translate("MainWindow", "自动验证"))
        self.manpower_radio.setText(_translate("MainWindow", "人工验证"))
        self.label.setText(_translate("MainWindow", "客户:"))
        self.label_2.setText(_translate("MainWindow", "机型:"))
        self.label_4.setText(_translate("MainWindow", "品名:"))
        self.label_6.setText(_translate("MainWindow", "料号:"))
        self.label_7.setText(_translate("MainWindow", "扫描输入条码:"))
        self.label_8.setText(_translate("MainWindow", "此次验证结果:"))
        self.result_txt.setPlaceholderText(_translate("MainWindow", "在此处显示扫描区接受数据的验证结果"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间"))
        item.setToolTip(_translate("MainWindow", "扫描的时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "结果判定"))
        item.setToolTip(_translate("MainWindow", "验证条码是否符合规则"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "序列号"))
        item.setToolTip(_translate("MainWindow", "扫描的条码"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "操作员"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "选项"))
        self.menu_3.setTitle(_translate("MainWindow", "设置"))
        self.menu_4.setTitle(_translate("MainWindow", "关于"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.ab_author_ac.setText(_translate("MainWindow", "关于作者"))
        self.ab_qt_ac.setText(_translate("MainWindow", "关于Qt"))
        self.theme_set_ac.setText(_translate("MainWindow", "首选项"))
        self.edit_plicy_ac.setText(_translate("MainWindow", "编辑规则"))
        self.edit_item_ac.setText(_translate("MainWindow", "编辑条目"))
        self.open_file_ac.setText(_translate("MainWindow", "打开文件"))
        self.close_file_ac.setText(_translate("MainWindow", "关闭文件"))
        self.exit_ac.setText(_translate("MainWindow", "退出"))
        self.ab_version_ac.setText(_translate("MainWindow", "关于版本"))
        self.action.setText(_translate("MainWindow", "注销"))
        self.logout_ac.setText(_translate("MainWindow", "注销"))
from .tools import MyLineEdit
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
